# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeCount = 1

  (1..NodeCount).each do |i|
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define "Ansibletower0#{i}" do |node|
      #node.vm.box = "roshankumarg/ELK"
      #node.vm.box = "centos/7"
      node.vm.box = "roshankumarg/AT"
      node.vm.box_version = "1.0.1"
      node.vm.hostname = "Ansibletower0#{i}.test"
      node.vm.network "private_network", ip: "172.42.42.10#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "Ansibletower0#{i}"
   	v.linked_clone = true
        v.memory = 5120
        v.cpus = 2
      end
    end
  end
end