---
- name: Install filebeat and metricbeat.
  become: true
  hosts: db
  gather_facts: false

  tasks:
    - name: Creating Elastic directory.
      file:
        path: /apps/elastic/
        state: directory

    - name: Copying Filebeat and Metricbeat Installation binaires to the servers.
      ansible.builtin.copy:
        src: beats.tar.gz
        dest: /apps/elastic/beats.tar.gz

    - name: Extract the Filebeat and Metricbeat binaires.      
      unarchive:
        src: /apps/elastic/beats.tar.gz
        dest: /apps/elastic/
        remote_src: True

    - name: Change file ownership, group and permissions for Elastic Directory.
      ansible.builtin.file:
        path: /apps/elastic
        owner: mwswls
        group: mwswls
        mode: 0750
        recurse: yes

    - name: Starting Filebeat and Metricbeat Agents.
      shell: /apps/elastic/elk_startup.sh > /tmp/Beats_Startup.txt ; cat /tmp/Beats_Startup.txt ; id
      args:
        executable: /bin/bash
      register: foo
      
    - debug: var=foo['stdout_lines']

    - name: Configure Filebeat and Metricbeat to run at boot.
      ansible.builtin.lineinfile:
        path: /apps/WF_Automation/scripts/welogic/weblogic_start
        regexp: '^BEATS'
        line: 'mwswls,/apps/elastic/elk_startup.sh ; sleep 30,'

    - name: Change file ownership, group and permissions for WF_Automation Directory
      ansible.builtin.file:
        path: /apps/WF_Automation
        owner: root
        group: root
        mode: 0755
        recurse: yes
