 
   - name: Add a new user named mwswls
     user:
          name=mwswls
          password=Long@123
 
   - name: Add mwswls user to the sudoers
     copy:
          dest: "/etc/sudoers.d/mwswls"
          content: "mwswls  ALL=(ALL)  NOPASSWD: ALL"
 
   - name: Deploy SSH Key
     authorized_key: user=mwswls
                     key="{{ lookup('file', 'id_rsa.pub') }}"
                     state=present
                     
   - name: Disable Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes

   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
           
     notify:
        - restart ssh
