---

    - name: Creating Elastic directory.
      file:
        path: "{{ Elastic_home }}"
        state: directory
        
    - name: Copying Filebeat and Metricbeat Installation binaires to the servers.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: "{{ Elastic_binaires }}"
          dest: "{{ Elastic_home }}/{{ Elastic_binaires }}"
        - src: "{{ Elastic_start_script }}"
          dest: "{{ Elastic_home }}/{{ Elastic_start_script }}"
        - src: "{{ Elastic_stop_script }}"
          dest: "{{ Elastic_home }}/{{ Elastic_stop_script }}"
        
    - name: Extract the Filebeat and Metricbeat binaires.      
      unarchive:
        src: "{{ Elastic_home }}/{{ Elastic_binaires }}"
        dest: "{{ Elastic_home }}"
        remote_src: True

    - name: Copying Filebeat configuration.
      copy:
        src: "{{ Filebeat_configuration_file }}"
        dest: "{{ Filebeat_location }}/{{ Filebeat_configuration_file }}"
    
    - name: Test filebeat configuration and backend output. 
      shell:
      args:
        cmd: ./filebeat test config ; ./filebeat test output ; 
        chdir: "{{ Filebeat_location }}"
        executable: /bin/bash
      register: Filebeat_out

    - debug: var=Filebeat_out['stdout_lines']

    - name: Change file ownership, group and permissions for Elastic Directory
      ansible.builtin.file:
        path: "{{ Elastic_home }}"
        owner: "{{ Elastic_username }}"
        group: "{{ Elastic_username }}"
        mode: 0750
        recurse: yes