---

    - name: Creating Elastic directory.
      file:
        path: /apps/elastic/
        state: directory
        
    - name: Copying Filebeat and Metricbeat Installation binaires to the servers.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: beats.tar.gz
          dest: /apps/elastic/beats.tar.gz
        - src: elk_startup.sh
          dest: /apps/elastic/elk_startup.sh
        
    - name: Extract the Filebeat and Metricbeat binaires.      
      unarchive:
        src: /apps/elastic/beats.tar.gz
        dest: /apps/elastic/
        remote_src: True

    - name: Change file ownership, group and permissions for Elastic Directory
      ansible.builtin.file:
        path: /apps/elastic
        owner: "{{ Elastic_username }}"
        group: "{{ Elastic_username }}"
        mode: 0750
        recurse: yes