---

    - name: Test filebeat configuration and backend Connection. 
      shell:
      args:
        cmd: ./filebeat test config ; ./filebeat test output ; 
        chdir: "{{ Filebeat_location }}"
        executable: /bin/bash
      register: Filebeat_out

    - debug: var=Filebeat_out['stdout_lines']

    - name: Test metricbeat configuration and backend Connection. 
      shell:
      args:
        cmd: ./metricbeat test config ; ./metricbeat test output ; 
        chdir: "{{ Metricbeat_location }}"
        executable: /bin/bash
      register: Metricbeat_out

    - debug: var=Metricbeat_out['stdout_lines']