---

    - name: Creating WFA directory.
      file:
        path: "{{ WFA_home }}/data/{{ WFA_product }}/"
        state: directory

    - name: "Searching for a String elk_startup"
      lineinfile:
        path: /apps/WF_Automation/data/weblogic/weblogic_start
        line: "elk_startup"
      check_mode: True
      register: presence
      failed_when: presence.changed 

    - name: "If elk_startup present in the file"
      debug: msg="elk_startup is enabled in WFA"
      when: presence is not changed

    - name: "Searching for a String elk_shutdown"
      lineinfile:
        path: /apps/WF_Automation/data/weblogic/weblogic_stop
        line: "elk_shutdown"
      check_mode: True
      register: presence
      failed_when: presence.changed

    - name: "If elk_shutdown present in the file"
      debug: msg="elk_shutdown is enabled in WFA"
      when: presence is not changed
        
    - name: Copying WFA Installation Configuration to the servers.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: "{{ WFA_start_script }}"
          dest: "{{ WFA_home }}/data/{{ WFA_product }}/{{ WFA_start_script }}"
        - src: "{{ WFA_stop_script }}"
          dest: "{{ WFA_home }}/data/{{ WFA_product }}/{{ WFA_stop_script }}"

    - name: Configure WFA for Filebeat and Metricbeat for start script  to run at boot.
      ansible.builtin.lineinfile:
        path: "{{ WFA_home }}/data/{{ WFA_product }}/{{ WFA_start_script }}"
        regexp: '^BEATS'
        line: "{{ Elastic_username }},{{ Elastic_home }}/{{ Elastic_start_script }}; sleep 30,"

    - name: Configure WFA for Filebeat and Metricbeat for stop script to run at boot.
      ansible.builtin.lineinfile:
        path: "{{ WFA_home }}/data/{{ WFA_product }}/{{ WFA_stop_script }}"
        regexp: '^BEATS'
        line: "{{ Elastic_username }},{{ Elastic_home }}/{{ Elastic_stop_script }}; sleep 30,"

    - name: Change file ownership, group and permissions for WF_Automation Directory
      ansible.builtin.file:
        path: "{{ WFA_home }}"
        owner: root
        group: root
        mode: 0755
        recurse: yes