metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 5s
  reload.enabled: true
processors:
- add_docker_metadata: ~
monitoring.enabled: true
setup.ilm.enabled: false

metricbeat.modules:
- module: apache
  metricsets: ["status"]
  period: 10s
  enabled: true
  # Apache hosts
  hosts: ["http://127.0.0.1:8888"]
  
output.elasticsearch:
  hosts: ["192.168.0.104:9200"]
  
logging.to_files: false
setup:
  kibana.host: "192.168.0.104:5601"
  dashboards.enabled: true
  
  