---

<<<<<<< HEAD
#Version 1.2, Rollbacked to Original.
=======
#Version 1.3
#new config added.
>>>>>>> f53e64b24846458caf5a5dad6d7bda92ba1d7a91

- hosts: app
  become: true
  become_user: root
  gather_facts: false
  roles:
    - Install_Beats_roles
    - Install_WFA_roles

- hosts: app
  become: true
  become_user: "{{ Elastic_username }}"
  gather_facts: false
  roles:
    - Start_Beats_Agent_roles
    