---

<<<<<<< HEAD
#Version 1.2
=======
#Install filebeat and metricbeat
>>>>>>> 8c9380f4f070c6425612893423e88415c32a0216

- hosts: app
  become: true
  become_user: root
  gather_facts: false
  roles:
    - Install_Beats_roles
    - Install_WFA_roles

- hosts: app
  become: true
  become_user: "{{ Elastic_username }}"
  gather_facts: false
  roles:
    - Start_Beats_Agent_roles
    